// Villages Seed Data for ตำบลเวียง อำเภอฝาง จังหวัดเชียงใหม่
// 20 หมู่บ้าน

export const villagesData = [
  {
    villageNo: 1,
    name: 'หนองตุ้ม',
    alternateNames: [],
    households: 120,
    population: 450,
    area: 5.2,
    description: 'หมู่บ้านหนองตุ้ม ตั้งอยู่ทางทิศเหนือของตำบล',
  },
  {
    villageNo: 2,
    name: 'ป่าบง',
    alternateNames: [],
    households: 95,
    population: 380,
    area: 4.8,
    description: 'หมู่บ้านป่าบง พื้นที่เกษตรกรรม',
  },
  {
    villageNo: 3,
    name: 'หนองอึ่ง',
    alternateNames: ['เวียงสุทโธ'],
    households: 150,
    population: 520,
    area: 6.5,
    description: 'หมู่บ้านหนองอึ่ง มีชื่อเรียกอีกชื่อว่า เวียงสุทโธ',
  },
  {
    villageNo: 4,
    name: 'สวนดอก',
    alternateNames: [],
    households: 110,
    population: 420,
    area: 5.0,
    description: 'หมู่บ้านสวนดอก พื้นที่ทำสวนดอกไม้',
  },
  {
    villageNo: 5,
    name: 'ต้นหนุน',
    alternateNames: [],
    households: 85,
    population: 340,
    area: 4.2,
    description: 'หมู่บ้านต้นหนุน',
  },
  {
    villageNo: 6,
    name: 'สันทรายคองน้อย',
    alternateNames: [],
    households: 130,
    population: 480,
    area: 5.8,
    description: 'หมู่บ้านสันทรายคองน้อย',
  },
  {
    villageNo: 7,
    name: 'แม่ใจใต้',
    alternateNames: [],
    households: 140,
    population: 510,
    area: 6.2,
    description: 'หมู่บ้านแม่ใจใต้ ตั้งอยู่ริมแม่น้ำแม่ใจ',
  },
  {
    villageNo: 8,
    name: 'แม่ใจเหนือ',
    alternateNames: [],
    households: 125,
    population: 465,
    area: 5.5,
    description: 'หมู่บ้านแม่ใจเหนือ ตั้งอยู่ริมแม่น้ำแม่ใจ',
  },
  {
    villageNo: 9,
    name: 'สันป่าไหน',
    alternateNames: [],
    households: 160,
    population: 580,
    area: 7.0,
    description: 'หมู่บ้านสันป่าไหน',
  },
  {
    villageNo: 10,
    name: 'สันป่ายาง',
    alternateNames: [],
    households: 105,
    population: 410,
    area: 4.9,
    description: 'หมู่บ้านสันป่ายาง',
  },
  {
    villageNo: 11,
    name: 'ท่าสะแล',
    alternateNames: [],
    households: 115,
    population: 440,
    area: 5.3,
    description: 'หมู่บ้านท่าสะแล',
  },
  {
    villageNo: 12,
    name: 'โป่งถืบ',
    alternateNames: [],
    households: 135,
    population: 495,
    area: 6.0,
    description: 'หมู่บ้านโป่งถืบ',
  },
  {
    villageNo: 13,
    name: 'ห้วยบอน',
    alternateNames: [],
    households: 90,
    population: 360,
    area: 4.5,
    description: 'หมู่บ้านห้วยบอน',
  },
  {
    villageNo: 14,
    name: 'เสาหิน',
    alternateNames: [],
    households: 100,
    population: 390,
    area: 4.7,
    description: 'หมู่บ้านเสาหิน',
  },
  {
    villageNo: 15,
    name: 'โป่งถืบใน',
    alternateNames: [],
    households: 80,
    population: 320,
    area: 4.0,
    description: 'หมู่บ้านโป่งถืบใน',
  },
  {
    villageNo: 16,
    name: 'ปางผึ้ง',
    alternateNames: [],
    households: 95,
    population: 375,
    area: 4.6,
    description: 'หมู่บ้านปางผึ้ง',
  },
  {
    villageNo: 17,
    name: 'ใหม่คองน้อย',
    alternateNames: [],
    households: 110,
    population: 425,
    area: 5.1,
    description: 'หมู่บ้านใหม่คองน้อย',
  },
  {
    villageNo: 18,
    name: 'ศรีดอนชัย',
    alternateNames: [],
    households: 120,
    population: 455,
    area: 5.4,
    description: 'หมู่บ้านศรีดอนชัย',
  },
  {
    villageNo: 19,
    name: 'ใหม่ชยาราม',
    alternateNames: [],
    households: 105,
    population: 405,
    area: 4.8,
    description: 'หมู่บ้านใหม่ชยาราม',
  },
  {
    villageNo: 20,
    name: 'สระนิคม',
    alternateNames: [],
    households: 125,
    population: 470,
    area: 5.6,
    description: 'หมู่บ้านสระนิคม',
  },
];
